plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'com.diffplug.spotless' version '8.9.0'
}

group = 'org.maboroshi'
def baseVersion = '1.0.0'

def getGitHash = { ->
    if (System.getenv("GITHUB_SHA") != null) {
        return System.getenv("GITHUB_SHA").take(6)
    }
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short=6'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    } catch (Exception ignored) {
        return "alpha"
    }
}

version = project.hasProperty('release') && project.property('release') == 'true' ?
          baseVersion : "${baseVersion}-${getGitHash()}"

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.extendedclip.com/releases/' }
    maven { url = 'https://repo.glaremasters.me/repository/towny/' }
    maven { url = 'https://nexus.scarsz.me/content/groups/public/' }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")
    compileOnly("de.exlll:configlib-paper:4.8.1")
    compileOnly("org.incendo:cloud-paper:2.0.0")
    compileOnly("org.incendo:cloud-annotations:2.1.0")
    implementation("org.bstats:bstats-bukkit:3.2.1")
    compileOnly("me.clip:placeholderapi:2.12.3")
    compileOnly("com.palmergames.bukkit.towny:towny:0.103.1.1")
    compileOnly("com.discordsrv:discordsrv:1.30.5")
    compileOnly("net.dv8tion:JDA:6.5.0")
}

tasks.register("printVersion") {
    group = "versioning"
    doLast {
        println("VERSION=${version}")
    }
}

tasks.named('shadowJar') {
    relocate 'org.bstats', 'org.maboroshi.yapper.libs.bstats'
    exclude 'plugin.yml'
    minimize()
    archiveClassifier.set('')
}

build.dependsOn shadowJar
build.dependsOn spotlessApply

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add("-parameters")
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}

spotless {
    format 'misc', {
        target '*.gradle', '.gitattributes', '.gitignore'
        trimTrailingWhitespace()
        leadingTabsToSpaces()
        endWithNewline()
    }

    java {
        importOrder()
        removeUnusedImports()
        forbidWildcardImports()
        cleanthat()
        palantirJavaFormat('2.96.0')
        formatAnnotations()
    }
}
