name: Yapper
version: ${version}
main: org.maboroshi.yapper.Yapper
loader: org.maboroshi.yapper.Loader
description: Customizable channels, proximity ranges, and interactive macros. Format messages with MiniMessage and share items or inventories directly in chat.
author: Maboroshi
website: https://github.com/MaboroshiKobo/Yapper
api-version: 26.1
folia-supported: true
modrinth-project-id: yapper
hangar-project-slug: yapper
github-repo: MaboroshiKobo/Yapper
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Towny:
      load: BEFORE
      required: false
    DiscordSRV:
      load: BEFORE
      required: false